[package]
name = "yew_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#antd = "0.12.1"
yew = "0.18.0"
antd-yew = "0.1.0"
log = "0.4.21"
